
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Nalin Kumar
tagline: Full Stack Developer
pic: nalin.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: nalinkmrr@gmail.com
phone: 09901730220
website: http://www.computerscijournal.org/vol10no1/noise-removal-and-filtering-techniques-used-in-medical-images/
linkedin: Nalin kumar
github: github.com/nalinkmr/
twitter: '@webjeda'

#Update all the sections by editing the files inside _includes folder.
